const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid'); // Import uuid library


const doctorSchema = new mongoose.Schema({
  doctorID: { type: String, default: uuidv4 }, // Autogenerated ID
  firstName: String,
  lastName: String,
  specialization: String,
  phoneNumbers: [String],
  experienceYears: Number,
  departmentID: String
});

module.exports = mongoose.model('Doctor', doctorSchema);
